### ISSUE TITLE
overriding output name?

### ISSUE THREAD

**Issue by willwade** [toubiweb/lwip-image-thumbnails-creator#1]
is it possible to override the output name? e.g. 

`{ outputbasepath: 'images/cache/thumbail.jpg'}`

and i really do want it named thumbnail.jpg - not thumbnail-w120-h120.jpg 

??

**Comment by Toub** [comment]
You can use the option { saveToDisk: false } to avoid the thumbnail to be created, then use the returned buffer or lwip image object:

``` javascript
var options = {
    saveToDisk: false
};
var inputpath = path.resolve(__dirname, './images/original-image.jpg');

thumbnailsCreator.createThumbnail(inputpath, {
    maxWidth: 600,
    maxHeight: 300
}, options).then(function (res) {

var outputpath = path.resolve(__dirname, './images/output/thumbnail-exact-name.jpg');

res.thumbnail.image.writeFile(outputpath, function(err){
    // if (err) ...
});

```

Unfortunately, there is a bug in the 0.0.2 version so the saveToDisk option is ignored. I will commit a patch very soon.

**Comment by Toub** [comment]
Sorry, the bug was in 0.0.1 version. You can now upgrade to 0.0.2 version and the example above should work.

I also updated the documentation.

Thanks for asking :-)
